DATA = {
    'homes': [
        {'id': 561726292,
         'curr_mode': 'A',
         'in_temp': 20,
         'out_temp': 10,
         'charge': 57,
         'sun_level': 90,
         'power_usage': 100,
         'cost': 0.5,
         'hot_water': 50,
         'pv_eff': 5, 
        },
        {'id': 560912392,
         'curr_mode': 'B',
         'in_temp': 18,
         'out_temp': 9,
         'charge': 93,
         'sun_level': 60,
         'power_usage': 50,
         'cost': 1.0,
         'hot_water': 30,
         'pv_eff': 7, 
        },
    ],
}